name: PDF Writeup to README
on: [push]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: contagon/PDFWriteupReadme@v1
      with:
        pdf-file: writeup.pdf
