name: PDF Writeup → README
on:
  push:
    paths:
      - 'writeup.pdf'
      - '.README.md'
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: contagon/PDFWriteupReadme@v1
      env:
        ORPHAN_BRANCH: images
        QUALITY: 90
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add README.md
        git commit -m "📄 Update README with PDF" || exit 0
        git push
